from __future__ import print_function

import os
import re

OUTPUT_DIR = os.path.join("output")
SQL_DIR = os.path.join("sql")
GENERATED_SQL = os.path.join(OUTPUT_DIR, "generated_create_tables.sql")

TEAM = os.environ.get("TEAM_NAME", "team20")
HDFS_USER_DIR = "/user/{}/project".format(TEAM)
WAREHOUSE_DIR = "{}/warehouse".format(HDFS_USER_DIR)
AVSC_DIR = "{}/avsc".format(WAREHOUSE_DIR)
HIVE_WAREHOUSE = "{}/hive/warehouse".format(HDFS_USER_DIR)
OUTPUT_HDFS = "{}/output".format(HDFS_USER_DIR)

HIVE_DB = "{}_projectdb".format(TEAM)

TABLES = ["train_transaction", "train_identity", "test_transaction", "test_identity"]

PG_TO_HIVE = {
    "BIGINT": "BIGINT",
    "SMALLINT": "INT",
    "NUMERIC": "DOUBLE",
    "TEXT": "STRING",
}

PARTITION_COL_PG = "isFraud"
PARTITION_COL_HIVE = "is_fraud"
BUCKET_COL = "transactionid"
NUM_BUCKETS = 4


def parse_pg_schema(sql_path):
    """Return {table_name: [(col_name_pg, hive_type), ...]} from generated DDL."""
    with open(sql_path) as fobj:
        content = fobj.read()

    tables = {}
    blocks = re.findall(
        r'CREATE TABLE "(\w+)"\s*\((.*?)\);',
        content,
        re.DOTALL,
    )
    for tname, block in blocks:
        cols = []
        for line in block.splitlines():
            line = line.strip().rstrip(",")
            if line.startswith("CONSTRAINT") or not line:
                continue
            match = re.match(r'"([^"]+)"\s+(\w+)', line)
            if match:
                col_pg = match.group(1)
                pg_type = match.group(2).upper()
                hive_type = PG_TO_HIVE.get(pg_type, "STRING")
                cols.append((col_pg, hive_type))
        tables[tname] = cols
    return tables


def col_lower(name):
    """Hive lowercases all column names."""
    return name.lower()


def external_table_hql(table, hdfs_loc, avsc_loc):
    """Generate CREATE EXTERNAL TABLE using Hive Avro SerDe."""
    lines = [
        "CREATE EXTERNAL TABLE IF NOT EXISTS {}".format(table),
        "ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.avro.AvroSerDe'",
        "STORED AS INPUTFORMAT 'org.apache.hadoop.hive.ql.io.avro.AvroContainerInputFormat'",
        "OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.avro.AvroContainerOutputFormat'",
        "LOCATION '{}'".format(hdfs_loc),
        "TBLPROPERTIES ('avro.schema.url'='{}');".format(avsc_loc),
    ]
    return "\n".join(lines)


def managed_pb_table_hql(schema):
    """Generate CREATE TABLE for train_transaction_pb (partitioned + bucketed)."""
    cols = schema.get("train_transaction", [])
    col_defs = []
    for col_pg, hive_type in cols:
        if col_pg == PARTITION_COL_PG:
            continue
        col_defs.append("    {} {}".format(col_lower(col_pg), hive_type))

    col_block = ",\n".join(col_defs)
    return (
        "CREATE TABLE IF NOT EXISTS train_transaction_pb (\n"
        "{}\n"
        ")\n"
        "PARTITIONED BY ({} INT)\n"
        "CLUSTERED BY ({}) INTO {} BUCKETS\n"
        "STORED AS ORC\n"
        "TBLPROPERTIES ('ORC.COMPRESS'='SNAPPY');".format(
            col_block, PARTITION_COL_HIVE, BUCKET_COL, NUM_BUCKETS
        )
    )


def insert_pb_hql(schema):
    """Generate INSERT OVERWRITE ... PARTITION for train_transaction_pb."""
    cols = schema.get("train_transaction", [])
    non_part = [col_lower(c) for c, _ in cols if c != PARTITION_COL_PG]
    part_src = [col_lower(c) for c, _ in cols if c == PARTITION_COL_PG]
    select_cols = non_part + part_src
    select_str = ",\n    ".join(select_cols)
    return (
        "SET hive.exec.dynamic.partition.mode=nonstrict;\n\n"
        "INSERT OVERWRITE TABLE train_transaction_pb PARTITION ({part})\n"
        "SELECT\n"
        "    {cols}\n"
        "FROM train_transaction;"
    ).format(part=PARTITION_COL_HIVE, cols=select_str)


def generate_tables_hql(schema):
    """Generate sql/stage2_tables.hql."""
    parts = []
    parts.append("-- Stage II: Hive table setup for {db}".format(db=HIVE_DB))
    parts.append("-- Generated by scripts/generate_stage2_hql.py")
    parts.append("")
    parts.append("DROP DATABASE IF EXISTS {db} CASCADE;".format(db=HIVE_DB))
    parts.append(
        "CREATE DATABASE IF NOT EXISTS {db}\n"
        "LOCATION '{loc}';".format(db=HIVE_DB, loc=HIVE_WAREHOUSE)
    )
    parts.append("USE {db};".format(db=HIVE_DB))
    parts.append("")

    for table in TABLES:
        hdfs_loc = "{}/{}/".format(WAREHOUSE_DIR, table)
        # avro.schema.url is resolved by Java SerDe; explicit hdfs:// scheme is required
        avsc_loc = "hdfs://{}/{}.avsc".format(AVSC_DIR, table)
        parts.append(external_table_hql(table, hdfs_loc, avsc_loc))
        parts.append("")

    parts.append(managed_pb_table_hql(schema))
    parts.append("")
    parts.append(insert_pb_hql(schema))
    return "\n".join(parts)


def q1_hql():
    return (
        "-- Q1: Fraud rate by product category\n"
        "SELECT\n"
        "    productcd,\n"
        "    COUNT(*) AS total_transactions,\n"
        "    SUM(is_fraud) AS fraud_count,\n"
        "    ROUND(SUM(is_fraud) * 100.0 / COUNT(*), 2) AS fraud_rate_pct\n"
        "FROM {db}.train_transaction_pb\n"
        "GROUP BY productcd\n"
        "ORDER BY fraud_rate_pct DESC;"
    ).format(db=HIVE_DB)


def q2_hql():
    return (
        "-- Q2: Fraud rate and average amount by transaction amount band\n"
        "SELECT\n"
        "    CASE\n"
        "        WHEN transactionamt < 10 THEN '01_lt10'\n"
        "        WHEN transactionamt < 50 THEN '02_10to50'\n"
        "        WHEN transactionamt < 100 THEN '03_50to100'\n"
        "        WHEN transactionamt < 500 THEN '04_100to500'\n"
        "        WHEN transactionamt < 1000 THEN '05_500to1000'\n"
        "        ELSE '06_ge1000'\n"
        "    END AS amount_band,\n"
        "    COUNT(*) AS total_transactions,\n"
        "    ROUND(AVG(transactionamt), 2) AS avg_amount,\n"
        "    SUM(is_fraud) AS fraud_count,\n"
        "    ROUND(SUM(is_fraud) * 100.0 / COUNT(*), 2) AS fraud_rate_pct\n"
        "FROM {db}.train_transaction_pb\n"
        "GROUP BY\n"
        "    CASE\n"
        "        WHEN transactionamt < 10 THEN '01_lt10'\n"
        "        WHEN transactionamt < 50 THEN '02_10to50'\n"
        "        WHEN transactionamt < 100 THEN '03_50to100'\n"
        "        WHEN transactionamt < 500 THEN '04_100to500'\n"
        "        WHEN transactionamt < 1000 THEN '05_500to1000'\n"
        "        ELSE '06_ge1000'\n"
        "    END\n"
        "ORDER BY amount_band;"
    ).format(db=HIVE_DB)


def q3_hql():
    return (
        "-- Q3: Fraud rate by card network (card4) and card type (card6)\n"
        "SELECT\n"
        "    card4,\n"
        "    card6,\n"
        "    COUNT(*) AS total_transactions,\n"
        "    SUM(is_fraud) AS fraud_count,\n"
        "    ROUND(SUM(is_fraud) * 100.0 / COUNT(*), 2) AS fraud_rate_pct\n"
        "FROM {db}.train_transaction_pb\n"
        "WHERE card4 IS NOT NULL AND card6 IS NOT NULL\n"
        "GROUP BY card4, card6\n"
        "ORDER BY fraud_rate_pct DESC;"
    ).format(db=HIVE_DB)


def q4_hql():
    return (
        "-- Q4: Top 25 payer email domains by transaction volume and fraud rate\n"
        "SELECT\n"
        "    p_emaildomain,\n"
        "    COUNT(*) AS total_transactions,\n"
        "    SUM(is_fraud) AS fraud_count,\n"
        "    ROUND(SUM(is_fraud) * 100.0 / COUNT(*), 2) AS fraud_rate_pct\n"
        "FROM {db}.train_transaction_pb\n"
        "WHERE p_emaildomain IS NOT NULL\n"
        "GROUP BY p_emaildomain\n"
        "ORDER BY total_transactions DESC\n"
        "LIMIT 25;"
    ).format(db=HIVE_DB)


def q5_hql():
    return (
        "-- Q5: Daily transaction volume and fraud rate over time\n"
        "-- transactiondt is seconds offset from a reference date\n"
        "SELECT\n"
        "    FLOOR(transactiondt / 86400) AS day_offset,\n"
        "    COUNT(*) AS total_transactions,\n"
        "    SUM(is_fraud) AS fraud_count,\n"
        "    ROUND(SUM(is_fraud) * 100.0 / COUNT(*), 2) AS fraud_rate_pct,\n"
        "    ROUND(AVG(transactionamt), 2) AS avg_amount\n"
        "FROM {db}.train_transaction_pb\n"
        "GROUP BY FLOOR(transactiondt / 86400)\n"
        "ORDER BY day_offset;"
    ).format(db=HIVE_DB)


def write_file(path, content):
    """Write content to path, creating parent directories if needed."""
    parent = os.path.dirname(path)
    if parent and not os.path.exists(parent):
        os.makedirs(parent)
    with open(path, "w") as fobj:
        fobj.write(content)
    print("Written: {}".format(path))


def main():
    if not os.path.exists(GENERATED_SQL):
        raise FileNotFoundError(
            "Run scripts/build_projectdb.py --generate-only first to produce {}".format(
                GENERATED_SQL
            )
        )

    schema = parse_pg_schema(GENERATED_SQL)

    tables_hql = generate_tables_hql(schema)
    write_file(os.path.join(SQL_DIR, "stage2_tables.hql"), tables_hql)

    for idx, hql_fn in enumerate([q1_hql, q2_hql, q3_hql, q4_hql, q5_hql], start=1):
        write_file(os.path.join(SQL_DIR, "q{}.hql".format(idx)), hql_fn())

    print("Stage II HQL files generated successfully.")


if __name__ == "__main__":
    main()
